# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goscany < Formula
  desc ""
  homepage "https://github.com/MarouaneBouaricha/goscany"
  version "0.0.5"

  on_macos do
    url "https://github.com/MarouaneBouaricha/goscany/releases/download/v0.0.5/goscany_0.0.5_darwin_all.tar.gz"
    sha256 "e5b2c66e79d47aa45121d20ff4afee912e16d17c797cfbbd6ea6404254fb7f49"

    def install
      bin.install "goscany"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/MarouaneBouaricha/goscany/releases/download/v0.0.5/goscany_0.0.5_linux_amd64.tar.gz"
      sha256 "3d86dcbc151a0a474fdc9694c7fe5a0d13751846f3aae66df5e1d676b15f047c"

      def install
        bin.install "goscany"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MarouaneBouaricha/goscany/releases/download/v0.0.5/goscany_0.0.5_linux_arm64.tar.gz"
      sha256 "4f1bceca5c0bd0e3e0f15c18cd91406e4f55ea64bd7c1e8947990b050306d74f"

      def install
        bin.install "goscany"
      end
    end
  end
end
